version: '2'
services:
    onhouse-app:
        image: onhouse
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://onhouse-mysql:3306/onhouse?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    onhouse-mysql:
        extends:
            file: mysql.yml
            service: onhouse-mysql
